AWSTemplateFormatVersion: "2010-09-09"

Resources: 
  # SourceBucket:
  #   Type: AWS::S3::Bucket
  #   Properties:
  #     BucketName: nycgroup05datalake

  DestinationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: grp-03-simulated-data

  IngestionGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: ingestion-transformation
      Role: arn:aws:iam::062024247186:role/LabRole
      GlueVersion: 4.0
      NumberOfWorkers: 10
      Timeout: 120
      WorkerType: G.1X
      Command:
        Name: glueetl
        ScriptLocation: s3://script-for-glue-3/glue-script.py
      DefaultArguments:
        "--job-language": "python"
      ExecutionProperty:
        MaxConcurrentRuns: 1


  GlueWorkflow:
    Type: AWS::Glue::Workflow
    Properties:
      Description: ETL Job
      MaxConcurrentRuns: 1
      Name: simulated-workflow

  GlueTriggerImport:
    Type: AWS::Glue::Trigger
    DependsOn:
      - GlueWorkflow
      - IngestionGlueJob
    Properties:
      Actions:
        - JobName: !Ref IngestionGlueJob
      Description: Triggers the Import Jobs
      Name: trigger-glue-import
      Type: EVENT
      WorkflowName: simulated-workflow




  GlueDatabase:
        Type: AWS::Glue::Database
        Properties:
            CatalogId: !Ref AWS::AccountId
            DatabaseInput:
                Name: simulated-db

  DataCrawler:
    Type: AWS::Glue::Crawler
    DependsOn:
      # - SourceBucket
      - DestinationBucket
      - GlueDatabase
      - GlueWorkflow
      # - GlueTriggerTransform
    Properties:
      Name: data-crawler7
      DatabaseName: simulated-db # Replace with your desired Glue database name
      Targets:
        S3Targets:
          - Path: s3://grp-03-simulated-data/ # Specify the path of the bucket you want to crawl
      Role: arn:aws:iam::062024247186:role/LabRole


  GlueTriggerForCrawler:
      Type: AWS::Glue::Trigger
      DependsOn:
        - GlueTriggerImport
      Properties:
        Name: GlueTriggerForCrawler
        Type: CONDITIONAL
        Actions:
          - CrawlerName: !Ref DataCrawler
            NotificationProperty:
              NotifyDelayAfter: 1
        Predicate:
          Conditions:
            - JobName: !Ref IngestionGlueJob
              LogicalOperator: EQUALS
              State: SUCCEEDED
          Logical: AND
        Type: CONDITIONAL
        StartOnCreation: True
        WorkflowName: simulated-workflow
  


      
